apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: container-application-challenge
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: database
    spec:
      imagePullSecrets:
        - name: github-registry
      containers:
        - env:
            - name: POSTGRES_DB
              value: secret
            - name: POSTGRES_PASSWORD
              valueFrom: 
                secretKeyRef:
                  name: database-credentials
                  key: DB_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: DB_USERNAME 
          image: docker.pkg.github.com/aeisl/container-application-challenge/database:latest
          imagePullPolicy: IfNotPresent
          name: database
          resources: {}
          # Persistent volume configuration
          volumeMounts: # Volume Mount for Container
            - mountPath: /var/lib/postgresql/data
              name: database-storage
      volumes: # Volume Mount for Pod
        - name: database-storage
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      restartPolicy: Always
