version: '3'

services:
  quarkus-api:
    build: 
      context: app
      dockerfile: src/main/docker/Dockerfile.jvm
  
  proxy:
    build:
      context: ha-proxy
    volumes:
      - './ha-proxy:/usr/local/etc/haproxy/'
    environment:
      BACKEND_HOST: quarkus-api
      BACKEND_PORT: 8080
    ports:
      -  80:8080
      -  443:8443

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: james
      POSTGRES_PASSWORD: bond
      POSTGRES_DB: secret
    volumes:
      - ./db/postgres/initdb:/docker-entrypoint-initdb.d
