version: "3"

services:
  quarkus-api:
    build:
      context: app
      dockerfile: src/main/docker/Dockerfile.jvm
    environment: 
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}

  proxy:
    build:
      context: ha-proxy
    volumes:
      - "./ha-proxy:/usr/local/etc/haproxy/"
    environment:
      BACKEND_HOST: quarkus-api
      BACKEND_PORT: 8080
    ports:
      - 80:8080
      - 443:8443

  database:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    volumes:
      - ./db/postgres/initdb:/docker-entrypoint-initdb.d
