# TODO: Remove this secret once the Docker Images become public, it will no longer be required.

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOnsidXNlcm5hbWUiOiJhZWlzbCIsInBhc3N3b3JkIjoiZ2hwX0hSZE52d1JlUnRuUGxmZWRWS2w4eEJnQ3ZSV3BvNTN6aW1JRCIsImF1dGgiOiJZV1ZwYzJ3NloyaHdYMGhTWkU1MmQxSmxVblJ1VUd4bVpXUldTMnc0ZUVKblEzWlNWM0J2TlRONmFXMUpSQT09In19fQ==
metadata:
  name: github-registry