apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/server-snippet: |
      proxy_intercept_errors on;
      location @custom_503 {
        return 404 "<html>No service is available on the configured port.</html>";
      }
      error_page 503 @custom_503;

  name: challenge
  labels:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: container-application-challenge
spec:
  tls:
    - hosts:
        - challenge.test
      secretName: challenge-test-tls