apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: challenge
spec:
  tls:
    - hosts:
        - challenge.test
      secretName: challenge-test-tls

  defaultBackend:
    service:
      name: container-application-challenge
      port:
        number: 8080
  
  rules:
    - host: challenge.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: container-application-challenge
                port: 
                  number: 8080
      
